name: Hello Krishan

on:
  push:
    branches:
      - main   # branch name list format में होना चाहिए

jobs:
  greet:
    runs-on: ubuntu-latest   # runs-on (not run-on)

    steps:
      - name: Say hello to users
        run: echo "Hello Dosto"

      - name: Say hello to username
        run: echo "Hello $USER"
