name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      # 3️⃣ Upload static files as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # if your index.html is in root

      # 4️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
